name: "Tests"

on:
  push:
    branches: [master, dev]

jobs:
  hello-world:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello world
        run: echo 'echo Welcome to the Github Actions workshop !'

  unit-tests:
    runs-on: ubuntu-20.04
    container: docker://epitechcontent/epitest-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        shell: bash
        run: make tests_run

      - name: Get coverage
        if: ${{ always() }}
        shell: bash
        run: make coverage > coverage_outputs

      - name: coverage artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: coverage_outputs
          path: ./coverage_outputs

  functional-tests:
    runs-on: ubuntu-20.04
    container: docker://epitechcontent/epitest-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        shell: bash
        run: bash functional-test.sh > functional_outputs

      - name: functional artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: functional_outputs
          path: ./functional_outputs