name: "Tests"

on: [push]

jobs: 
    build: hello-world
        branches:
            -master
            -dev
        runs-on: ubuntu-20.04
        steps:
            -name: Say hello world
            run: echo 'echo Welcome to the Github Actions workshop !'