name: "Tests"

on:
  push:
    branches: [master, dev]

jobs:
  hello-world:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello world
        run: echo 'echo Welcome to the Github Actions workshop !'
  unit-test:
    using: Docker
    image: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v2
      - name: Say hello world
        run: |
          make tests_run
          gcovr --exclude tests/