name: "Tests"

on:
  push:
    branches: [master, dev]

jobs:
  hello-world:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello world
        run: echo 'echo Welcome to the Github Actions workshop !'

  unit-test:
    runs-on: ubuntu-20.04
    container: docker://epitechcontent/epitest-docker
    steps:
      - name: Checkout
        uses: action/checkout@v2
      - name: Run tests
        shell: bash
        run: |
          make tests_run
          make coverage